resources:
  - deployment.yaml
  - mapping.yaml
  - service.yaml
  - rabbitmq-connection-sealed-secret.yaml
  - database-connection-sealed-secret.yaml
  - database-migration-connection-sealed-secret.yaml
  - namespace.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - database-migration-job.yaml
